/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmptyLayoutRouteImport } from './routes/_emptyLayout'
import { Route as BaseLayoutRouteImport } from './routes/_baseLayout'
import { Route as BaseLayoutIndexRouteImport } from './routes/_baseLayout/index'
import { Route as EmptyLayoutVerifyEmailRouteImport } from './routes/_emptyLayout/verify-email'
import { Route as EmptyLayoutSignupRouteImport } from './routes/_emptyLayout/signup'
import { Route as EmptyLayoutResetPasswordRouteImport } from './routes/_emptyLayout/reset-password'
import { Route as EmptyLayoutLoginRouteImport } from './routes/_emptyLayout/login'
import { Route as EmptyLayoutForgotPasswordRouteImport } from './routes/_emptyLayout/forgot-password'
import { Route as BaseLayoutDashboardRouteImport } from './routes/_baseLayout/dashboard'

const EmptyLayoutRoute = EmptyLayoutRouteImport.update({
  id: '/_emptyLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseLayoutRoute = BaseLayoutRouteImport.update({
  id: '/_baseLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseLayoutIndexRoute = BaseLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseLayoutRoute,
} as any)
const EmptyLayoutVerifyEmailRoute = EmptyLayoutVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => EmptyLayoutRoute,
} as any)
const EmptyLayoutSignupRoute = EmptyLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => EmptyLayoutRoute,
} as any)
const EmptyLayoutResetPasswordRoute =
  EmptyLayoutResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => EmptyLayoutRoute,
  } as any)
const EmptyLayoutLoginRoute = EmptyLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EmptyLayoutRoute,
} as any)
const EmptyLayoutForgotPasswordRoute =
  EmptyLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => EmptyLayoutRoute,
  } as any)
const BaseLayoutDashboardRoute = BaseLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BaseLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseLayoutIndexRoute
  '/dashboard': typeof BaseLayoutDashboardRoute
  '/forgot-password': typeof EmptyLayoutForgotPasswordRoute
  '/login': typeof EmptyLayoutLoginRoute
  '/reset-password': typeof EmptyLayoutResetPasswordRoute
  '/signup': typeof EmptyLayoutSignupRoute
  '/verify-email': typeof EmptyLayoutVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseLayoutIndexRoute
  '/dashboard': typeof BaseLayoutDashboardRoute
  '/forgot-password': typeof EmptyLayoutForgotPasswordRoute
  '/login': typeof EmptyLayoutLoginRoute
  '/reset-password': typeof EmptyLayoutResetPasswordRoute
  '/signup': typeof EmptyLayoutSignupRoute
  '/verify-email': typeof EmptyLayoutVerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_baseLayout': typeof BaseLayoutRouteWithChildren
  '/_emptyLayout': typeof EmptyLayoutRouteWithChildren
  '/_baseLayout/dashboard': typeof BaseLayoutDashboardRoute
  '/_emptyLayout/forgot-password': typeof EmptyLayoutForgotPasswordRoute
  '/_emptyLayout/login': typeof EmptyLayoutLoginRoute
  '/_emptyLayout/reset-password': typeof EmptyLayoutResetPasswordRoute
  '/_emptyLayout/signup': typeof EmptyLayoutSignupRoute
  '/_emptyLayout/verify-email': typeof EmptyLayoutVerifyEmailRoute
  '/_baseLayout/': typeof BaseLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
  id:
    | '__root__'
    | '/_baseLayout'
    | '/_emptyLayout'
    | '/_baseLayout/dashboard'
    | '/_emptyLayout/forgot-password'
    | '/_emptyLayout/login'
    | '/_emptyLayout/reset-password'
    | '/_emptyLayout/signup'
    | '/_emptyLayout/verify-email'
    | '/_baseLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BaseLayoutRoute: typeof BaseLayoutRouteWithChildren
  EmptyLayoutRoute: typeof EmptyLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_emptyLayout': {
      id: '/_emptyLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmptyLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_baseLayout': {
      id: '/_baseLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_baseLayout/': {
      id: '/_baseLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseLayoutIndexRouteImport
      parentRoute: typeof BaseLayoutRoute
    }
    '/_emptyLayout/verify-email': {
      id: '/_emptyLayout/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof EmptyLayoutVerifyEmailRouteImport
      parentRoute: typeof EmptyLayoutRoute
    }
    '/_emptyLayout/signup': {
      id: '/_emptyLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof EmptyLayoutSignupRouteImport
      parentRoute: typeof EmptyLayoutRoute
    }
    '/_emptyLayout/reset-password': {
      id: '/_emptyLayout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof EmptyLayoutResetPasswordRouteImport
      parentRoute: typeof EmptyLayoutRoute
    }
    '/_emptyLayout/login': {
      id: '/_emptyLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof EmptyLayoutLoginRouteImport
      parentRoute: typeof EmptyLayoutRoute
    }
    '/_emptyLayout/forgot-password': {
      id: '/_emptyLayout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof EmptyLayoutForgotPasswordRouteImport
      parentRoute: typeof EmptyLayoutRoute
    }
    '/_baseLayout/dashboard': {
      id: '/_baseLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof BaseLayoutDashboardRouteImport
      parentRoute: typeof BaseLayoutRoute
    }
  }
}

interface BaseLayoutRouteChildren {
  BaseLayoutDashboardRoute: typeof BaseLayoutDashboardRoute
  BaseLayoutIndexRoute: typeof BaseLayoutIndexRoute
}

const BaseLayoutRouteChildren: BaseLayoutRouteChildren = {
  BaseLayoutDashboardRoute: BaseLayoutDashboardRoute,
  BaseLayoutIndexRoute: BaseLayoutIndexRoute,
}

const BaseLayoutRouteWithChildren = BaseLayoutRoute._addFileChildren(
  BaseLayoutRouteChildren,
)

interface EmptyLayoutRouteChildren {
  EmptyLayoutForgotPasswordRoute: typeof EmptyLayoutForgotPasswordRoute
  EmptyLayoutLoginRoute: typeof EmptyLayoutLoginRoute
  EmptyLayoutResetPasswordRoute: typeof EmptyLayoutResetPasswordRoute
  EmptyLayoutSignupRoute: typeof EmptyLayoutSignupRoute
  EmptyLayoutVerifyEmailRoute: typeof EmptyLayoutVerifyEmailRoute
}

const EmptyLayoutRouteChildren: EmptyLayoutRouteChildren = {
  EmptyLayoutForgotPasswordRoute: EmptyLayoutForgotPasswordRoute,
  EmptyLayoutLoginRoute: EmptyLayoutLoginRoute,
  EmptyLayoutResetPasswordRoute: EmptyLayoutResetPasswordRoute,
  EmptyLayoutSignupRoute: EmptyLayoutSignupRoute,
  EmptyLayoutVerifyEmailRoute: EmptyLayoutVerifyEmailRoute,
}

const EmptyLayoutRouteWithChildren = EmptyLayoutRoute._addFileChildren(
  EmptyLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BaseLayoutRoute: BaseLayoutRouteWithChildren,
  EmptyLayoutRoute: EmptyLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
